python train.py --dataset=cora                     --model=linear_ae    --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_cora__linear_ae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=cora                     --model=linear_vae   --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_cora__linear_vae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=cora                     --model=gcn_ae       --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora__gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora                     --model=gcn_vae      --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora__gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora                     --model=deep_gcn_ae  --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora__deep_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora                     --model=deep_gcn_vae --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora__deep_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora     --features=True --model=linear_ae    --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_cora_features_linear_ae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=cora     --features=True --model=linear_vae   --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_cora_features_linear_vae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=cora     --features=True --model=gcn_ae       --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora_features_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora     --features=True --model=gcn_vae      --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora_features_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora     --features=True --model=deep_gcn_ae  --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora_features_deep_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=cora     --features=True --model=deep_gcn_vae --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_cora_features_deep_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer                 --model=linear_ae    --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer__linear_ae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=citeseer                 --model=linear_vae   --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer__linear_vae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=citeseer                 --model=gcn_ae       --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer__gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer                 --model=gcn_vae      --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer__gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer                 --model=deep_gcn_ae  --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer__deep_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer                 --model=deep_gcn_vae --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer__deep_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer --features=True --model=linear_ae    --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 >..\results\reproduce_citeseer_features_linear_ae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=citeseer --features=True --model=linear_vae   --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer_features_linear_vae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=citeseer --features=True --model=gcn_ae       --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer_features_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer --features=True --model=gcn_vae      --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer_features_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer --features=True --model=deep_gcn_ae  --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer_features_deep_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=citeseer --features=True --model=deep_gcn_vae --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_citeseer_features_deep_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed                   --model=linear_ae    --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed__linear_ae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=pubmed                   --model=linear_vae   --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed__linear_vae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=pubmed                   --model=gcn_ae       --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed__gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed                   --model=gcn_vae      --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed__gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed                   --model=deep_gcn_ae  --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed__deep_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed                   --model=deep_gcn_vae --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed__deep_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed   --features=True --model=linear_ae    --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed_features_linear_ae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=pubmed   --features=True --model=linear_vae   --task=link_prediction --epochs=200 --learning_rate=0.01             --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed_features_linear_vae_link_prediction_200_0.01__16_50.txt
python train.py --dataset=pubmed   --features=True --model=gcn_ae       --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed_features_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed   --features=True --model=gcn_vae      --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed_features_gcn_vae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed   --features=True --model=deep_gcn_ae  --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed_features_deep_gcn_ae_link_prediction_200_0.01_32_16_50.txt
python train.py --dataset=pubmed   --features=True --model=deep_gcn_vae --task=link_prediction --epochs=200 --learning_rate=0.01 --hidden=32 --dimension=16 --nb_run=50 > ..\results\reproduce_pubmed_features_deep_gcn_vae_link_prediction_200_0.01_32_16_50.txt